[build]
  publish = "/"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = []
  included_files = ["netlify/functions/**"]
  node_version = "18"
